### ISSUE TITLE
календарь

### ISSUE THREAD

**Issue by Kroshy1984** [Kroshy1984/SimplePsy#142]

**Comment by Breadlyy** [comment]
![image](https://github.com/user-attachments/assets/ef85cf75-daee-45d3-8661-d93926fd9237)
![image](https://github.com/user-attachments/assets/81996b08-8701-4224-9fca-071c11aa46c2)
![image](https://github.com/user-attachments/assets/0067b0db-7d41-4509-812f-973698acf92e)
