### ISSUE TITLE
раскатать базу данных

### ISSUE THREAD

**Issue by Kroshy1984** [Kroshy1984/SimplePsy#34]
[creds.txt](https://github.com/Kroshy1984/SimplePsy/files/13242272/creds.txt)
1. надо подключиться к серверу RuDVS
2. зайти в Ubuntu
3. Открыть терминал
4. залить базу данных

**Comment by shmvsky** [comment]
# Раскатал бд
## Подключение к серваку
![image](https://github.com/Kroshy1984/SimplePsy/assets/90981162/c7249055-ce80-453d-a304-29c574a4e2f3)

![image](https://github.com/Kroshy1984/SimplePsy/assets/90981162/624813ce-0f97-4442-a6cd-6cf97b12691b)


## Подключение к постгресу

```bash
psql -U test_user test_db -h 127.0.0.1
```

## pgAdmin 4
### Конфигурация сервера
![image](https://github.com/Kroshy1984/SimplePsy/assets/90981162/414438ce-87d4-474e-b801-3e33a92bb275)

![image](https://github.com/Kroshy1984/SimplePsy/assets/90981162/9a636b9d-8a8c-43a2-a955-d26d229a62c6)

### Получаем вот это
![image](https://github.com/Kroshy1984/SimplePsy/assets/90981162/c0e2c0b7-613b-49de-a178-81ba8f1639f5)

**Comment by shmvsky** [comment]
```shell
apt update
apt install postgresql postgresql-contrib
systemctl start postgresql
su postgres -c psql
```

**Comment by Kroshy1984** [comment]
база данных раскатана
