### ISSUE TITLE
связь многие ко многим

### ISSUE THREAD

**Issue by Kroshy1984** [Kroshy1984/SimplePsy#39]
как сделать связь многие ко многим

**Comment by Sumchenko** [comment]
### **Связь многие ко многим**

При отношении _"многие-ко-многим"_ одной записи одной таблицы может соответствовать несколько записей второй таблицы, а одной записи второй таблицы - несколько записей первой.Этот вид отношений, как правило, можно установить только между двумя таблицами, связанными с помощью третьей (связующей) таблицы, которая состоит из первичных ключей двух первых таблиц.

![image](https://github.com/Kroshy1984/SimplePsy/assets/121259144/6840f847-6d9a-4ab7-91b9-a4a79f05d754)

**Comment by Kroshy1984** [comment]
вопрос закрыт
